version: 0.2

phases:
  pre_build:
    commands:
      - ls -la

  build:
    commands:
      - echo CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub -> ${CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub}
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION -> ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo CODEBUILD_SOURCE_VERSION -> ${CODEBUILD_SOURCE_VERSION}
      - echo Testing Core on `date`
      - sbt clean coverage test

      - echo Generating coverage report
      - sbt coverageReport

      - echo Submit coverage report to Codacy
      - sbt codacyCoverage

  post_build:
    commands:
      - echo Build completed on `date`