version: 0.2

phases:
  pre_build:
    commands:
      - ls -la
      - java -version
      - echo "${CODEBUILD_SOURCE_VERSION}"

  build:
    commands:
      - echo Testing Core on `date`
      - sbt clean coverage test

      - echo Generating coverage report
      - "if [[ $CODEBUILD_SOURCE_VERSION =~ [0-9a-f]{5,40} ]] ; then sbt coverageReport; fi"
      -

      - echo Submit coverage report to Codacy
      - "if [[ $CODEBUILD_SOURCE_VERSION =~ [0-9a-f]{5,40} ]] ; then sbt codacyCoverage; fi"

  post_build:
    commands:
      - echo Build completed on `date`