version: 0.2

phases:
  pre_build:
    commands:
      - ls -la
      - java -version
      - echo "${CODEBUILD_SOURCE_VERSION}"

  build:
    commands:
      - echo Testing Core on `date`
      - sbt clean coverage test

      - echo Generating coverage report
      - sbt coverageReport

      - echo Submit coverage report to Codacy
      - sbt codacyCoverage

  post_build:
    commands:
      - echo Build completed on `date`