version: 0.2

phases:
  pre_build:
    commands:
      - ls -la
      - java -version
      - echo "${CODEBUILD_SOURCE_VERSION}"
      - chmod +x submit_coverage.sh

  build:
    commands:
      - echo Testing Core on `date`
      - sbt clean coverage test

      - echo Submit coverage report to Codacy
      - ./submit_coverage.sh


  post_build:
    commands:
      - echo Build completed on `date`