iamRoleStatements:
  - Effect: "Allow"
    Action:
      - sns:Publish
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-error-topic-arn"
  - Effect: Allow
    Action:
      - sqs:SendMessageBatch
      - sqs:SendMessage
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"
  - Effect: Allow
    Action: cloudwatch:PutMetricData
    Resource: "*"
  # =======================================================================
  # ADD CUSTOM PERMISSIONS HERE
  # =======================================================================

environment:
  REPORT_EXCEPTION: false
  LOG_LEVEL: DEBUG
  STAGE_NAME: ${self:custom.stageName}
  APP_NAME: ${self:service}

custom:
  stageName: ${opt:stage, self:provider.stage}

